### ISSUE TITLE
Normals are not properly oriented

### ISSUE THREAD

**Issue by el-dee** [Moguri/panda3d-gltf#48]
When testing the normals and normal maps using https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/NormalTangentMirrorTest one can see that the normals are not correctly oriented: 

This is the output of the viewer :

<img width="912" alt="Wrong normalmap" src="https://user-images.githubusercontent.com/44778133/72263867-02aa8280-361a-11ea-8864-23f65b5f11a3.png">

This is the expected output :

![screenshot-larger](https://user-images.githubusercontent.com/44778133/72263882-0d651780-361a-11ea-9810-6944f7950c4c.png)

As one can see, the orientation of the specular reflection and the shading is not the same across all column as it should have been.

One root cause could be that the axis conversion from Y-up to Z-up is not properly applied on both the normal and the tangent.

**Comment by el-dee** [comment]
If I skip axis conversion, there is no more problem wrt the normals.

<img width="912" alt="NoConversion" src="https://user-images.githubusercontent.com/44778133/72277509-588b2480-3632-11ea-92da-230788e2cdda.png">

In _ATTRIB_CONTENT_MAP the 'tangent' entry  is associated with GeomEnums.C_other, but changing it to GeomEnums.C_vector does not fix the problem, it introduces even more artefacts.

**Comment by Moguri** [comment]
Taking a look at `Geom.transform_verticies()` it only applies to C_point and C_vector. C_other (what we use for tangent since we use 4 components instead of the 3 Panda expects for C_vector) C_morph_delta, and C_normal are not covered. We already handle c_morph_data ourselves. I tried something similar with C_normal, but still couldn't get things right. I probably need to handle tangent transforms as well, which means figuring out how to deal with the w-component. I tried re-calculating the tangents after the transform, but I suspect this particular example file won't work right with generated tangents.

**Comment by el-dee** [comment]
>  I tried re-calculating the tangents after the transform, but I suspect this particular example file won't work right with generated tangents.

That's the purpose of the sample, to test that the loader really uses the provided normals and not generate the normals using the geometry. So in a sense,  it's a good news that it doesn't work doing that :-)

**Comment by el-dee** [comment]
Fixed in #73
