### ISSUE TITLE
Exporting or loading Multiple Armatures doesn't work.

### ISSUE THREAD

**Issue by fireclawthefox** [Moguri/panda3d-gltf#68]
When trying to load a model with two armatures using the Actor class, only one of them seem to get loaded. The other armature and also the model parented to it are not visible in the application.
If I try and load the model as a static model, both objects are displayed. There also is a difference in the shading. The Actor loaded model seems to be shadeless while the static models are shaded.
Loading the bam file with pview also only shows the static model and no animations get loaded.

A sample code with blend and bam file showing the problem:
[TwoArmatures.tar.gz](https://github.com/Moguri/panda3d-gltf/files/4633012/TwoArmatures.tar.gz)

**Comment by rdb** [comment]
This is actually a problem with Actor, not with panda3d-gltf.  Actor only supports a single character; it looks for the Character node, and yanks it out of the scene to parent it to the Actor itself.  This is also the reason for the lighting loss, since the LightAttrib is applied on a parent node of the Actor.

To remedy this, you probably want to create one separate Actor per armature.  Try this:
```python
from direct.showbase.ShowBase import ShowBase
from direct.actor.Actor import Actor

base = ShowBase()

model = loader.loadModel("TwoArmatures.bam")
model.reparentTo(render)
model.setY(25)

actorA = Actor(model.find("**/A"), copy=False)
actorA.reparentTo(model)
actorB = Actor(model.find("**/B"), copy=False)
actorB.reparentTo(model)

print(actorA.getAnimNames())
print(actorB.getAnimNames())

actorA.loop('ArmatureAction')
#actorB.loop('Armature.001Action')

base.run()
```

We *might* want to consider having panda3d-gltf apply the LightAttrib at a lower level than the scene level, but I think we should rather address this properly in Panda3D, either by fixing Actor or by adding proper documentation.

Feel free to file a new issue upstream for this.  We could have Actor automatically create a single subpart actor when used in this situation, as also suggested in panda3d/panda3d#457.

**Comment by Moguri** [comment]
I am going to close this as an upstream limitation. @fireclawthefox if you feel this report should still be open, then we can re-open it.
